# Generated by Django 5.1.5 on 2025-01-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JapanAlphabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('symbols', models.CharField(max_length=10, verbose_name='Symbols')),
                ('full_text', models.TextField(verbose_name='Full text')),
            ],
        ),
    ]
